git branch -f observables_backup observables
git branch -f architecture_backup architecture
git branch -f forms_backup forms
git branch -f routing_backup routing
git branch -f redux_backup redux
git branch -f ngrx_backup ngrx
git branch -f testing_backup testing
#git branch -f reusable-libraries_backup reusable-libraries
git branch -f pwa_backup pwa
git branch -f universal_backup universal
